app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[ 
    path('bye/',bye,name='bye'),
]

project3/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import * 

urlpatterns=[
    path('admin/', admin.site.urls),
    path('hi/',hi,name='hi'),
    path('hello/',hello,name='hello'),
    path('bye/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def hi(request):
    return render(request,'hi.html')
def hello(request):
    return render(request,'hello.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is bye html file</h1>
        <h6><a href="{% url 'hi' %}">navigate to hi</a></h6>
        <h6><a href="{% url 'hello' %}">navigate to hello</a></h6>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this hello html file</h1>
        <h6><a href="{% url 'hi' %}">navigate to hai</a></h6>
        <h6><a href="{% url 'app2:bye' %}">navigate to bye</a></h6>
    </center>
</body>
</html>

templates/hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is hi html file</h1>
        <h6><a href="{% url 'hello' %}">navigate to hello</a></h6>
        <h6><a href="{% url 'app2:bye' %}">navigate to bye</a></h6>
    </center>
</body>
</html>